call plug#begin('~/.vim/plugged')
Plug 'joshdick/onedark.vim'
Plug 'morhetz/gruvbox'
Plug 'ghifarit53/tokyonight-vim'
Plug 'sirver/ultisnips'
Plug 'honza/vim-snippets'
Plug 'preservim/nerdtree'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'jiangmiao/auto-pairs'
call plug#end()

set number
set cursorline
set showmode
syntax on"enable
set background=dark

"tokyonight-vim
let g:tokyonight_style = 'night' "night, storm
let g:tokyonight_enable_italic = 0
"set termguicolors
let g:tokyonight_transparent_background = 1
let g:tokyonight_disable_italic_comment = 0
let g:tokyonight_menu_selection_background = 'green' "green, red, blue
let g:tokyonight_cursor = 'auto' "red, green, blue
let g:tokyonight_current_word = 'grey background'
"Available values: 'bold', 'underline', 'italic', 'grey background'
colorscheme tokyonight

"nerdtree
nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-t> :NERDTree<CR>
nnoremap <C-n> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>
"let NERDTreeShowHidden=1
let NERDTreeQuitOnOpen=1
"let g:NERDTreeFileLines=1

"ultisnips
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
let g:UltiSnipsEditSplit="vertical"

"vim-airline-themes
let g:airline_theme='tokyonight'
let g:airline#extensions#tabline#enabled = 0
let g:airline#extensions#tabline#formatter = 'unique_tail'

"auto-pairs
let g:AutoPairsFlyMode = 0
let g:AutoPairsShortcutBackInsert = '<c-b>'
